### ISSUE TITLE
Can't bind variable in sql query

### ISSUE THREAD

**Issue by iranapex** [APEXGru/JET-PictoChart#2]
The plugin does not allow to use bind variable in where clause.

**Comment by APEXGru** [comment]
You are correct. And that is intentionally. The purpose of this plugin is to demonstrate the most simple (thus basic) way to integrate JET Charts in APEX.
You can add it yourself - see the StatusMeterGauge Plugin for the example code. As that one contains all (?) the features you might want / need in a plugin.
